 "use client";
import {useEffect,useRef,useState} from "react";
type Step="home"|"camera"|"analysis"|"results"|"collection"|"preview"|"barber";
const styles=[["Two Block",94,"Modern","Bagian atas medium, sisi ringan."],["Low Fade",91,"Clean","Fade rendah yang aman untuk daily."],["Textured Crop",88,"Casual","Pendek, bertekstur, mudah ditata."],["Comma Hair",86,"Korean","Fringe melengkung dengan volume ringan."],["French Crop",84,"Short","Rapi dan praktis untuk aktivitas."],["Middle Part",82,"Medium","Natural dengan belahan tengah."]];
const collection=["Two Block","Low Fade","Textured Crop","Comma Hair","Middle Part","French Crop","Crew Cut","Ivy League","Buzz Cut","Short Quiff","Side Part","Slick Back","Pompadour","Curtain Hair","Wolf Cut","Mullet","Curly Top","Spiky Hair","Undercut","Taper Fade","Drop Fade","Crop Fade","Comb Over","Messy Hair"];
export default function Topsid(){
const [step,setStep]=useState<Step>("home"),[photo,setPhoto]=useState<string|null>(null),[sel,setSel]=useState(styles[0]),[camera,setCamera]=useState(false),[recording,setRecording]=useState(false),[sec,setSec]=useState(0),[progress,setProgress]=useState(0);
const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number|null>(null);
useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current)},[]);
async function openCamera(){setStep("camera");try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});stream.current=s;setCamera(true);setTimeout(()=>{if(video.current)video.current.srcObject=s},50)}catch{setCamera(false)}}
function stop(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false)}
function analyze(){setStep("analysis");setProgress(0);let p=0;const t=setInterval(()=>{p+=10;setProgress(p);if(p>=100){clearInterval(t);setTimeout(()=>setStep("results"),300)}},160)}
function capture(){if(!video.current)return;const c=document.createElement("canvas"),v=video.current;c.width=v.videoWidth||720;c.height=v.videoHeight||960;c.getContext("2d")?.drawImage(v,0,0,c.width,c.height);setPhoto(c.toDataURL("image/jpeg",.88));stop();setRecording(false);analyze()}
function record(){if(recording){capture();return}setRecording(true);setSec(0);timer.current=setInterval(()=>setSec(s=>{if(s>=4){if(timer.current)clearInterval(timer.current);setTimeout(capture,100);return 5}return s+1}),1000)}
function choose(s:any){setSel(s);setStep("preview")}
function reset(){stop();setPhoto(null);setProgress(0);setRecording(false);setSec(0);setStep("home")}
return <main className="site">
<header><button className="logo" onClick={reset}><span> T </span><b>TOPSID<small>CEK DULU. BARU POTONG.</small></b></button><button className="menu">☰</button></header>
<nav>{["Rekam","Analisis","Rekomendasi","Preview","Barber"].map((x,i)=><span key={x}><i>{i+1}</i>{x}</span>)}</nav>
{step==="home"&&<section className="home"><div><label>TOP'S COLLECTION • AI HAIRSTYLE CHECK</label><h1>Gaya yang cocok,<em> sebelum dipotong.</em></h1><p>Rekam wajahmu sebentar. TOPSID membantu menemukan gaya rambut yang paling pas buat kamu.</p><button className="cta" onClick={openCamera}>◉ &nbsp; Mulai Cek Rambut</button><small>Gratis 3 rekomendasi / hari • Tanpa daftar</small></div><div className="poster"><strong>TOP'S</strong><b>COLLECTION</b><div>{collection.slice(0,12).map((x,i)=><article key={x}><span>{["◉","◒","◐","◓"][i%4]}</span><small>{x}</small></article>)}</div><footer>30 GAYA TERBAIK</footer></div></section>}
{step==="camera"&&<section className="screen"><button className="back" onClick={()=>{stop();setStep("home")}}>← Kembali</button><label>STEP 01 • REKAM</label><h2>Rekam wajahmu <em>secara perlahan.</em></h2><p className="sub">Posisikan wajah di dalam oval, lalu hadap depan, sedikit ke kiri dan kanan.</p><div className="camera">{camera?<video ref={video} autoPlay playsInline muted/>:<div className="fallback"><span>👨🏻</span><b>Kamera belum aktif</b><button onClick={openCamera}>Aktifkan Kamera</button></div>}<div className="guide"/></div><div className="controls"><small>00:{String(sec).padStart(2,"0")}</small><button className={recording?"rec active":"rec"} onClick={record}><i/></button><small>↻</small></div><p className="hint">{recording?"Hadap depan → kiri → kanan":"Tekan tombol untuk merekam ±5 detik"}</p>{!camera&&<label className="gallery">Atau pilih foto dari galeri<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{setPhoto(String(r.result));analyze()};r.readAsDataURL(f)}}}/></label>}</section>}
{step==="analysis"&&<section className="screen center"><label>STEP 02 • ANALISIS AI</label><h2>Mengenali wajah <em>dan rambutmu...</em></h2><div className="analysis"><div>{photo?<img src={photo} alt="Foto"/>:<span>👨🏻</span>}<b>{progress}%</b></div>{["Bentuk wajah","Tekstur rambut","Ketebalan rambut","Garis rambut","Proporsi wajah"].map((x,i)=><p key={x}><i>{progress>i*20?"✓":"·"}</i>{x}</p>)}</div><aside>🔒 Foto hanya digunakan untuk analisis.</aside></section>}
{step==="results"&&<section className="screen"><label>STEP 03 • HASIL ANALISIS</label><h2>Ini 3 gaya terbaik <em>untukmu.</em></h2><div className="profile"><span>Wajah <b>Oval</b></span><span>Rambut <b>Lurus</b></span><span>Ketebalan <b>Sedang</b></span></div><div className="list">{styles.slice(0,3).map((s,i)=><article key={s[0]}><b className="rank">{i+1}</b><div className="stylepic">{photo?<img src={photo} alt=""/>:<span>{["✦","◒","✂"][i]}</span>}</div><div><small>{s[2]}</small><h3>{s[0]}</h3><p>{s[3]}</p><strong>Cocok {s[1]}%</strong></div><button onClick={()=>choose(s)}>Coba di wajahku →</button></article>)}</div><button className="outline wide" onClick={()=>setStep("collection")}>Lihat TOP'S Collection • 30 gaya</button></section>}
{step==="collection"&&<section className="screen"><button className="back" onClick={()=>setStep("results")}>← Hasil untukmu</button><label>TOP'S COLLECTION</label><h2>30 gaya. <em>Pilih yang kamu suka.</em></h2><div className="filters"><button>Semua</button><button>Pendek</button><button>Medium</button><button>Panjang</button></div><div className="grid">{collection.map((x,i)=><button key={x} onClick={()=>choose(styles[i%styles.length])}><span>{["◉","◒","◐","◓"][i%4]}</span><b>{x}</b></button>)}</div></section>}
{step==="preview"&&<section className="screen"><button className="back" onClick={()=>setStep("results")}>← Rekomendasi</button><label>STEP 04 • PREVIEW</label><h2><em>{sel[0]}</em><br/>di wajahmu.</h2><div className="preview">{photo?<img src={photo} alt="Preview"/>:<span>👨🏻</span>}<b>PREVIEW DEMO</b></div><div className="angles"><button>Depan</button><button>Samping</button><button>45°</button></div><div className="summary"><span>KECOCOKAN<strong>{sel[1]}%</strong></span><span>GAYA<strong>{sel[0]}</strong></span><span>PERAWATAN<strong>Easy</strong></span></div><button className="cta wide" onClick={()=>setStep("barber")}>✂ Tunjukkan ke Barber</button><button className="ghost" onClick={()=>setStep("results")}>Coba gaya lain</button><small className="demo">Preview AI asli disambungkan pada tahap API.</small></section>}
{step==="barber"&&<section className="screen"><label>STEP 05 • BARBER CARD</label><h2>Siap dibawa <em>ke barber.</em></h2><div className="barber"><header><div><small>TOPSID RECOMMENDS</small><h3>{sel[0]}</h3><b>Cocok {sel[1]}%</b></div><strong>TOPSID</strong></header><div className="barberpic">{photo?<img src={photo} alt=""/>:<span>👨🏻</span>}</div><div className="specs"><span>SAMPING<b>Low taper / fade</b></span><span>ATAS<b>5–7 cm, textured</b></span><span>STYLING<b>Matte / natural</b></span></div><p>“Mas, saya mau model seperti ini. Bagian samping dibuat ringan, atas tetap natural.”</p></div><div className="actions"><button className="cta" onClick={()=>alert("Demo: Barber Card siap dibagikan.")}>↗ Bagikan</button><button className="ghost" onClick={reset}>Selesai</button></div></section>}
<footer className="foot"><b>TOPSID</b><span>Cek dulu. Baru potong.</span><span>© 2026</span></footer>
</main>}
